### ISSUE TITLE
In Chroms for Mac doesn't works...

### ISSUE THREAD

**Issue by gabrielizalo** [lukevp/pluralsight-transcript#1]
Appears this error:

```
Error in event handler for runtime.onMessage: TypeError: Cannot read property 'classList' of null
    at updateTranscript (chrome-extension://ciabocebgmaodclhcngdonkbljlfclcc/transcript.js:80:47)
    at handleMessage (chrome-extension://ciabocebgmaodclhcngdonkbljlfclcc/transcript.js:117:9)
    at chrome-extension://ciabocebgmaodclhcngdonkbljlfclcc/browser-polyfill.min.js:1:5888
```

**Comment by lukevp** [comment]
Thank you for the report!
